name: Apollo_Automation-CI
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches: [ main, release]
  pull_request:
    branches: [ main, release]
  workflow_dispatch:
     inputs:
       tags:
         description: 'Apollo WDIO Automation Testing'
jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PUBLISH_BRANCH: gh-pages
      PUBLISH_DIR: allure-history
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
